### ISSUE TITLE
侧滑会导致navigationItem.rightBarButtonItem跑掉

### ISSUE THREAD

**Issue by poholo** [AugustRush/ARTransitionAnimator#6]
侧滑会导致navigationItem.rightBarButtonItem跑掉，不知道作者有没有碰到过，期待回复，🙏

**Comment by AugustRush** [comment]
有截图或者demo吗？

**Comment by poholo** [comment]
我搞错了，不好一次，现在定位到可能是另外一个库导致的，不好意思。

**Comment by poholo** [comment]
我搞错了，现在定位到可能是另外一个库导致的，不好意思。
